server {
    listen 80;
    server_name _;
    root /usr/share/nginx/html;
    index index.html;

    location /api/accounts/ { proxy_pass http://accounts-service:8000; }
    location /api/catalog/ { proxy_pass http://catalog-service:8000; }
    location /api/observations/ { proxy_pass http://observation-service:8000; }
    location /api/community/ { proxy_pass http://community-service:8000; }

    location / { try_files $uri $uri/ /index.html; }
}
